[build-system]
requires = [
    'hatchling',
    'hatch-regex-commit',
]
build-backend = 'hatchling.build'


[project]
name = 'AgentBranch'
authors = [
    {name = 'Randy Syring', email = 'randy@syrings.us'},
]
requires-python = '~=3.13.0'
dynamic = ['version']
readme = 'readme.md'


[project.scripts]
'abra' = 'abra.cli:main'


[dependency-groups]
dev = [
    {include-group = "pytest"},
    {include-group = "prek"},
    {include-group = "audit"},
    {include-group = "nox"},
    'click',
    'hatch',
    'ruff',
]
# Used by nox
pytest = [
    'pytest',
    'pytest-cov',
]
# Used by nox
prek = [
    "prek>=0.3.10",
]
# Used by nox
audit = [
    'pip-audit',
]
# Used by CI
nox = [
    'nox',
]
